SET(UQUAD_CPU_ARCHITECTURE "arm64" CACHE STRING "CPU architectures")
SET_PROPERTY(CACHE UQUAD_CPU_ARCHITECTURE PROPERTY STRINGS "armv7;armv7 armv7s;arm64;armv7 armv7s arm64")
#STRING(REPLACE " " "+" UQUAD_CPU_ARCHITECTURE ${UQUAD_CPU_ARCHITECTURE})

SET(CMAKE_OSX_ARCHITECTURES ${UQUAD_CPU_ARCHITECTURE})
SET(CMAKE_XCODE_ATTRIBUTE_VALID_ARCHS ${UQUAD_CPU_ARCHITECTURE})

SET(UQUAD_IOS_DEPLOYMENT_TARGET "9.0" CACHE STRING "iOS deployment target")
SET_PROPERTY(CACHE UQUAD_IOS_DEPLOYMENT_TARGET PROPERTY STRINGS "5.1;6.0;6.1;7.0;7.1;8.0;9.0;9.1")

SET(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET ${UQUAD_IOS_DEPLOYMENT_TARGET})

SET(UQUAD_IOS_TARGETED_DEVICE_FAMILY "iPhone" CACHE STRING "Targeted iOS device family")
SET_PROPERTY(CACHE UQUAD_IOS_TARGETED_DEVICE_FAMILY PROPERTY STRINGS "iPhone;iPad;iPhone/iPad")

IF(UQUAD_IOS_TARGETED_DEVICE_FAMILY STREQUAL iPhone)
	SET(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1")
ELSEIF(UQUAD_IOS_TARGETED_DEVICE_FAMILY STREQUAL iPad)
	SET(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "2")
ELSE()
	SET(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")
ENDIF()


SET(CMAKE_XCODE_ATTRIBUTE_GCC_VERSION "com.apple.compilers.llvm.clang.1_0")
SET(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
SET(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")

SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS_INIT} -fvisibility=hidden -fvisibility-inlines-hidden")
SET(CMAKE_C_FLAGS_DEBUG "-g -O0")
SET(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -O2")
SET(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_INIT} -Wall -fvisibility=hidden -fvisibility-inlines-hidden -ftemplate-depth=1024 -Wno-error=c++11-narrowing")
SET(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O2")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")

SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_CXX_FLAGS_INIT} -dead_strip")

MACRO(UQUAD_ADD_EXECUTABLE NAME)
	SET(MACOSX_BUNDLE_GUI_IDENTIFIER "com.uquad.${NAME}")
	ADD_EXECUTABLE(${NAME} MACOSX_BUNDLE
		${ARGN}
	)
	SET_TARGET_PROPERTIES(${APP}
		PROPERTIES
			XCODE_ATTRIBUTE_INSTALL_PATH "$(LOCAL_APPS_DIR)"
			XCODE_ATTRIBUTE_SKIP_INSTALL "NO"
	)
	
	SET_TARGET_PROPERTIES(${APP} PROPERTIES MACOSX_BUNDLE_BUNDLE_NAME "\${PRODUCT_NAME}")
ENDMACRO(UQUAD_ADD_EXECUTABLE)

MACRO(UQUAD_INSTALL_EXECUTABLE NAME)
ENDMACRO(UQUAD_INSTALL_EXECUTABLE)

MACRO(UQUAD_ENABLE_PRECOMPILED_HEADERS TARGET HEADER)
	GET_FILENAME_COMPONENT(HEADER_ABSOLUTE ${HEADER} ABSOLUTE)
	SET_TARGET_PROPERTIES(${TARGET} 
		PROPERTIES
	    XCODE_ATTRIBUTE_GCC_PREFIX_HEADER "${HEADER_ABSOLUTE}"
		XCODE_ATTRIBUTE_GCC_PRECOMPILE_PREFIX_HEADER "YES"
	)
ENDMACRO(UQUAD_ENABLE_PRECOMPILED_HEADERS)

MACRO(UQUAD_ADD_TEST NAME TEST_APP)
ENDMACRO(UQUAD_ADD_TEST)