GET_FILENAME_COMPONENT(UQUAD_CMAKE_CONFIG_CMAKE_PATH "${CMAKE_CURRENT_LIST_FILE}" PATH)
INCLUDE(CMakeParseArguments)

IF(CMAKE_HOST_APPLE)
	SET(UQT_COMMAND "${UQUAD_CMAKE_CONFIG_CMAKE_PATH}/bin/Mac/uqt")
ENDIF()


IF(APPLE AND NOT IOS_PLATFORM)
    SET(UQUAD_PLATFORM_MAC 1)
    SET(UQUAD_PLATFORM Mac)
ELSEIF(WIN32)
    SET(UQUAD_PLATFORM_WIN 1)
    SET(UQUAD_PLATFORM Win)
ELSEIF(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT ANDROID)
    SET(UQUAD_PLATFORM_LINUX 1)
    SET(UQUAD_PLATFORM Linux)
ELSEIF(APPLE AND IOS_PLATFORM)
    SET(UQUAD_PLATFORM_IOS 1)
    SET(UQUAD_PLATFORM iOS)
ELSEIF(ANDROID)
    SET(UQUAD_PLATFORM_ANDROID 1)
    SET(UQUAD_PLATFORM Android)
ELSE()
    MESSAGE(FATAL_ERROR "Unsupported platform!")
ENDIF()

INCLUDE(${UQUAD_CMAKE_CONFIG_CMAKE_PATH}/Platform/${UQUAD_PLATFORM}/Config.cmake)

add_definitions(
	-DUQUAD_PLATFORM_${UQUAD_PLATFORM}
)
